name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Get dependencies
      run: go get .

    - name: Build
      run: go build .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug
        path: ${{ github.workspace }}/idRehashGo
