name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build

    - name: Build
      run: cmake --build ${{ github.workspace }}/build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug
        path: ${{ github.workspace }}/build/idRehash

  test-static:
    runs-on: ubuntu-latest
    env:
      IDREHASHLINUX_STATIC: '1'

    steps:
    - uses: actions/checkout@v3

    - name: Setup Alpine
      uses: jirutka/setup-alpine@v1
      with:
        branch: v3.17

    - name: Install dependencies
      run: apk add build-base cmake
      shell: alpine.sh --root {0}

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build
      shell: alpine.sh {0}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build
      shell: alpine.sh {0}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug-static
        path: ${{ github.workspace }}/build/idRehash
